2019-02-12 15:41:13,890 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:46]
2019-02-12 20:27:33,647 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:46]
2019-02-12 20:34:37,981 ERROR: Exception on /reset_password_request [POST] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\app\routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "d:\dev\microblog\venv\app\email.py", line 21, in send_password_reset_email
    user=user, token=token))
  File "d:\dev\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "d:\dev\microblog\venv\app\templates\email\reset_password.html", line 1, in template
    <p> Dear {{ user.username </p>
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 480, in parse_compare
    ops.append(nodes.Operand(token_type, self.parse_math1()))
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 583, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "d:\dev\microblog\venv\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '/'
2019-02-12 21:11:16,537 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:46]
2019-02-12 21:11:40,234 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTUwMDAyODg5LjAyNjUzMn0.5P6EiLM_Y3l_5GogsOzWjH2-LiIaehQprKgMH78b3js [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\app\routes.py", line 186, in reset_password
    user = User.verify_reset_password_token(token)
AttributeError: type object 'User' has no attribute 'verify_reset_password_token'
2019-02-12 21:13:28,748 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTUwMDAyOTk4LjcwODI2Mjd9.DzDxPylexoQAqTzo3Z5cD2IWPQTKL3mEvyfLMGhQR8E [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\app\routes.py", line 186, in reset_password
    user = User.verify_reset_password_token(token)
AttributeError: type object 'User' has no attribute 'verify_reset_password_token'
2019-02-12 21:14:36,337 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTUwMDAzMDY0Ljk4OTY1MTJ9.lXP9Txt02OgcOwGR4FilyHSvXsUpWLq-scn2zGiX0eg [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\app\routes.py", line 186, in reset_password
    user = User.verify_reset_password_token(token)
AttributeError: type object 'User' has no attribute 'verify_reset_password_token'
